/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ccb102143e4de0f26ed5234084518580)
interface __BaseEnv_Env {
	RATE_LIMITER: RateLimit;
	GITHUB_REPO: "owner/repository";
	GITHUB_LABEL: "user-feedback";
	FEEDBACK_REPORTS: DurableObjectNamespace<import("./src/index").FeedbackReport>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FeedbackReport";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPO" | "GITHUB_LABEL">> {}
}
