/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 97d08387d2963cc71bb636ef5ae9f1d3)
interface __BaseEnv_Env {
	RATE_LIMITER: RateLimit;
	GITHUB_REPO: "owner/repository";
	GITHUB_LABEL: "user-feedback";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPO" | "GITHUB_LABEL">> {}
}
